{{- if (hasSuffix "-test" .Release.Namespace)}}

apiVersion: batch/v1
kind: Job
metadata:
  labels:
{{- include "cas-registration.labels" . | nindent 4 }}
    component: backend
  name: {{ template "cas-registration.fullname" . }}-restore-test-users
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: {{ template "cas-registration.fullname" . }}-restore-test-users
      labels:
{{- include "cas-registration.labels" . | nindent 8 }}
        component: backend
    spec:
      activeDeadlineSeconds: 180
      containers:
        - name:  {{ template "cas-registration.fullname" . }}-restore-test-users
          image: postgres:16.6-alpine
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: cas-obps-postgres-pguser-postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cas-obps-postgres-pguser-postgres
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: cas-obps-postgres-pguser-postgres
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: cas-obps-postgres-pguser-postgres
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: cas-obps-postgres-pguser-postgres
          command:
            - /usr/bin/env
            - bash
            - -c
            - |
              psql -c "insert into erc.user(select * from preserve.user);";
              psql -c "drop schema preserve cascade;";
      restartPolicy: Never
{{ end }}
