# Temporary values for Monorepo-supported cas registration with cas-reporting.
# This should deploy into a namespace to trial the side-by-side deployments.

# This forces {include "cas-registration.fullname"} to use our temporary naming.
fullnameOverride: cas-bciers

backend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-bciers-backend-dev.apps.silver.devops.gov.bc.ca

  environment: develop

  deployRoute: true

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 60m
      memory: 256Mi

registration1Frontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca

  environment: develop

  auth:
    keycloakAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logontest7.gov.bc.ca

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 60m
      memory: 256Mi

reportingFrontend:
  enabled: true

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/reportingpath"

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 60m
      memory: 256Mi
